workflows:
  godot-android-workflow:
      name: Godot Android Workflow
      max_build_duration: 60
      environment:
        groups:
          - godot
        vars:
          GODOT_VERSION: 4.3
          GODOT_EXEC_URL: https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip
          GODOT_TEMPLATES_URL: https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_export_templates.tpz
          GODOT_EXEC: Godot_v${GODOT_VERSION}-stable_x11.64
          EXPORT_TYPE: android
          ARTIFACT: android_build.apk
          ANDROID_SDK_PATH: /path/to/android-sdk
          ANDROID_NDK_PATH: /path/to/android-ndk
      scripts:
        - name: Download Godot engine
          script: curl -o ./godot.zip ${GODOT_EXEC_URL} && unzip ./godot.zip
        - name: Download Godot templates
          script: curl -o ./godot-templates.zip ${GODOT_TEMPLATES_URL} && unzip ./godot-templates.zip
        - name: Setup SDK and NDK
          script: export PATH=${ANDROID_SDK_PATH}/tools:${ANDROID_SDK_PATH}/platform-tools:${ANDROID_NDK_PATH}/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
        - name: Prepare build directory
          script: mkdir build/
        - name: Decode export presets
          script: echo ${GODOT_EXPORT_PRESETS} | base64 --decode > ./export_presets.cfg
        - name: Export project
          script:  - godot --verbose --path . --no-window --export "${EXPORT_TYPE}" build/${ARTIFACT}
      artifacts:
        - build/*.apk
