workflows:
  godot-android-workflow:
    name: Godot Android Workflow
    max_build_duration: 60
    environment:
      groups:
        - godot
      vars:
        GODOT_VERSION: 4.3
        GODOT_EXEC_URL: https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_macos.universal.zip
        GODOT_TEMPLATES_URL: https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz
        GODOT_TEMPLATES_DIR: "$PWD/godot/templates/${GODOT_VERSION}.stable"
        GODOT_EXEC: Godot.app/Contents/MacOS/Godot
        EXPORT_TYPE: "android"
        ARTIFACT: app.apk
    scripts:
      - name: Download Godot engine
        script: curl -o ./godot.zip ${GODOT_EXEC_URL} && unzip ./godot.zip
      - name: Download Godot templates
        script: curl -o ./godot-templates.tpz ${GODOT_TEMPLATES_URL} && unzip ./godot-templates.tpz -d ./templates
      - name: Setup templates
        script: mkdir -p "${GODOT_TEMPLATES_DIR}" && mv templates/* "${GODOT_TEMPLATES_DIR}/"
      - name: Prepare build directory
        script: mkdir build/
      - name: Decode export presets
        script: echo ${GODOT_EXPORT_PRESETS} | base64 --decode > ./export_presets.cfg
      - name: Export project
        script: ${GODOT_EXEC} --path . --no-window --export-release "${EXPORT_TYPE}" build/${ARTIFACT}
    artifacts:
      - build/*.apk
