workflows:
  godot-android-workflow:
      name: Godot Android Workflow
      max_build_duration: 60
      environment:
        groups:
          - godot
        vars:
          GODOT_VERSION: 4.3
          GODOT_EXEC_URL: https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip
          GODOT_TEMPLATES_URL: https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_export_templates.tpz
          GODOT_EXEC: Godot_v${GODOT_VERSION}-stable_x11.64
          EXPORT_TYPE: android
          ARTIFACT: android_build.apk
          ANDROID_SDK_PATH: /path/to/android-sdk
          ANDROID_NDK_PATH: /path/to/android-ndk
      scripts:
        - name: Download Godot engine
          script: |
            # Baixar o Godot (versão 4.3)
            mkdir -p /godot
            wget -O /godot/godot.zip https://downloads.tuxfamily.org/godotengine/4.3/godot-4.3-stable-linux-x86_64.zip
            unzip /godot/godot.zip -d /godot
            chmod +x /godot/godot.x86_64
        - name: Export project
          script: |
            # Navegar para o diretório do projeto Godot
            cd $CM_BUILD_DIR
            
            # Configurar o export template se necessário
            wget https://downloads.tuxfamily.org/godotengine/4.3/godot-4.3-android-export.zip
            unzip godot-4.3-android-export.zip -d ~/.local/share/godot/templates

            # Gerar o APK
            /godot/godot.x86_64 --export "Android" --no-window "project.godot" "builds/android_project.apk"
      artifacts:
        - build/*.apk
